# Generated by Django 3.2.3 on 2021-08-29 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('gender', models.IntegerField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], null=True, verbose_name='جنسیت')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users/profile_images/', verbose_name='تصویر')),
                ('balance', models.IntegerField(default=0, verbose_name='اعتبار')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'نمایه کاربری',
                'verbose_name_plural': 'نمایه کاربری',
            },
        ),
    ]
